# Generated by Django 4.2.1 on 2023-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_participant', models.CharField(blank=True, max_length=100)),
                ('prenom_du_participant', models.CharField(blank=True, max_length=100)),
                ('numero_du_participant', models.CharField(max_length=10)),
                ('email_du_participant', models.EmailField(max_length=254)),
            ],
        ),
    ]
